# Generated by Django 5.2.1 on 2025-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0021_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
