# Generated by Django 5.2.1 on 2025-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0022_remove_vehicle_fuel_type_vehicle_load_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
