# Generated by Django 5.2.1 on 2025-11-17 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0023_alter_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='logistics_app.load')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
