# Generated by Django 5.2.1 on 2025-11-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0024_loadrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='load',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to='logistics_app.driver'),
        ),
        migrations.AddField(
            model_name='load',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loads', to='logistics_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='load',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.CharField(help_text='e.g. 10 Ton, 20T, 15.5 Heavy', max_length=50),
        ),
    ]
