# Generated by Django 5.2.1 on 2025-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0025_alter_load_options_load_assigned_at_load_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='10% of total amount - paid after delivery', max_digits=12),
        ),
        migrations.AddField(
            model_name='load',
            name='first_half_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='90% of total amount - paid at loading', max_digits=12),
        ),
        migrations.AlterField(
            model_name='load',
            name='drop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
