# Generated by Django 5.2.1 on 2025-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0026_load_final_payment_load_first_half_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('lr_uploaded', 'LR Uploaded'), ('first_half_payment', 'First Half Payment'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('pod_uploaded', 'POD Uploaded'), ('payment_completed', 'Payment Completed')], default='pending', help_text='Detailed trip progress status', max_length=20),
        ),
    ]
