# Generated by Django 5.2.1 on 2025-11-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0027_load_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='first_half_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='lr_document',
            field=models.FileField(blank=True, help_text='Upload LR (Lorry Receipt) document', null=True, upload_to='lr_documents/'),
        ),
        migrations.AddField(
            model_name='load',
            name='lr_number',
            field=models.CharField(blank=True, help_text='LR Number/Reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='lr_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='lr_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pod_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='unloading_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
