# Generated by Django 5.2.1 on 2025-11-20 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0028_load_first_half_payment_at_load_in_transit_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['-created_at'], 'verbose_name': 'Load', 'verbose_name_plural': 'Loads'},
        ),
        migrations.RemoveField(
            model_name='load',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='load',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='10% balance – auto-calculated', max_digits=14),
        ),
        migrations.AlterField(
            model_name='load',
            name='first_half_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='90% advance payment – user enters this amount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='lr_document',
            field=models.FileField(blank=True, null=True, upload_to='lr_documents/'),
        ),
        migrations.AlterField(
            model_name='load',
            name='lr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('lr_uploaded', 'LR Uploaded'), ('first_half_payment', 'First Half Payment'), ('in_transit', 'In Transit'), ('unloading', 'Unloading'), ('pod_uploaded', 'POD Uploaded'), ('payment_completed', 'Payment Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 10 Ton, 20T', max_length=50, null=True),
        ),
    ]
