# Generated by Django 5.2.1 on 2025-11-20 06:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0029_alter_load_options_remove_load_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='load',
            name='first_half_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
