# Generated by Django 5.2.1 on 2025-11-20 06:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0030_alter_load_final_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Price Per Unit (Full Freight Amount)'),
        ),
    ]
