# Generated by Django 5.2.1 on 2025-11-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0031_load_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pod_document',
            field=models.FileField(blank=True, null=True, upload_to='pod_documents/'),
        ),
        migrations.AddField(
            model_name='load',
            name='pod_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pods', to=settings.AUTH_USER_MODEL),
        ),
    ]
