# Generated by Django 5.2.1 on 2025-11-21 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0032_load_pod_document_load_pod_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor/Owner')], help_text='Type of sender (admin or vendor)', max_length=10)),
                ('comment', models.TextField(help_text='The message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the comment was last updated')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the comment has been read by the recipient')),
                ('load', models.ForeignKey(help_text='The load/trip this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logistics_app.load')),
                ('sender', models.ForeignKey(help_text='The user who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='trip_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Comment',
                'verbose_name_plural': 'Trip Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['load', 'created_at'], name='logistics_a_load_id_f66dce_idx'), models.Index(fields=['sender', 'created_at'], name='logistics_a_sender__76b811_idx')],
            },
        ),
    ]
